apiVersion: apps/v1
kind: Deployment
metadata:
  name: homedynip
spec:
  selector:
    matchLabels:
      app: homedynip
  template:
    metadata:
      labels:
        app: homedynip
    spec:
      containers:
        - name: homedynip
          image: golgoth31/homedynip:latest
          args:
            - server
          env:
            - name: HOMEDYNIP_SERVER_PORT
              value: "8080"
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - name: http
              containerPort: 8080
