logLevel: info
logFormat: console
client:
  service: ipify
  url: http://localhost:8080
  insecure: false
  cron: false
  sleep: 1h
  dryrun: false
  dns: ovh

server:
  port: 8080

ovh:
  username: xxxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxx
  hostname: xxxxxxxxxxxxxxxxx

noip:
  username: xxxxxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxx
  hostname: xxxxxxxxxxxxxxxxx
